messages = ["<b>Shoulder-arm stretch</b>Time to do Shoulder arm stretch, keep one arm horizontally stretched in front of your chest. Push this arm with your other arm towards you until you feel a mild tension in your shoulder. Hold this position briefly, and repeat the exercise for your other arm. Don't do this more than 40 seconds.",
"<b>Finger stretch</b> Time to do finger stretch, Separate and stretch your fingers until a mild tension is felt, and hold this for 10 seconds. Relax, then bend your fingers at the knuckles, and hold again for 10 seconds. Repeat this exercise once more. Time duration is 40 seconds.",
"<b>Neck tilt stretch</b> Time to do neck tilt streatch, Start with your head in a comfortable straight position. Then, slowly tilt your head to your right shoulder to gently stretch the muscles on the left side of your neck. Hold this position for 5 seconds. Then, tilt your head to the left side to stretch your other side. Do this twice for each side. Time duration is 30 seconds.",
"<b>Backward shoulder stretch</b> Time to do backward shoulder stretch, Interlace your fingers behind your back. Then turn your elbows gently inward, while straightening your arms. Hold this position for 5 to 15 seconds, and repeat this exercise twice. Time duration is 30 seconds.",
"<b>Move the eyes</b> Look at the upper left corner of the outside border of your monitor. Follow the border slowly to the upper right corner. Continue to the next corner, until you got around it two times. Then, reverse the exercise. Total time duration is 32 seconds.",
"<b>Train focusing the eyes</b> Look for the furthest point you can see behind your monitor. Focus your eyes on the remote point. Then focus on your monitor border. Repeat it. If you cannot look very far from your monitor, face another direction with a longer view. Then switch your focus between a distant object and a pen held at the same distance from your eyes as your monitor.",
"<b>Look into the darkness</b> Cover your eyes with your palms in such way that you can still open your eyelids. Now open your eyes and look into the darkness of your palms. This exercise gives better relief to your eyes compared to simply closing them. You can do this for 20 seconds",
"<b>Move the shoulders</b> Spin your right arm slowly round like a plane propeller beside your body. Do this 4 times forwards, 4 times backwards and relax for a few seconds. Repeat with the left arm. You can do this for 30 seconds.",
"<b>Move the shoulders up and down</b> Put your hands on the armrests of your chair when you are sitting down and press your body up until your arms are straight. Try to move your head even further by lowering your shoulders. Slowly move back into your chair.Please do this 30 seconds only.",
"<b>Turn your head</b> Turn your head left and keep it there for 2 seconds. Then turn your head right and keep it there for 2 seconds. You can do this for 2 seconds."
"<b>Relax the eyes</b> Close your eyes and breathe out as long as you can and try to relax. When breathing in, again do it as slowly as possible. Try to count slowly to 8 for each time you breathe in and out. To extra relax your eyes, try closing them in micro pauses too. You can do this for 12 seconds."]
